### ISSUE TITLE
When crossing dividers, there is a tiny chance that player will drop the flag, despite not being killed

### ISSUE THREAD

**Issue by VenkSociety** [buildist/CTFServer#5]
From what I've seen, it's a very rare bug, only seen it twice myself but others have reported more incidents. Due to the reliability of the bug, was not able to replicate it fully but I have deduced that it could be due to players crossing the divider with the flag.

Untested but it could also be due to two flag carriers. From the two instances I've seen, both teams had taken the flag but I can't vouch for if this has happened with the other folk.

**Comment by dakriy** [comment]
Are you sure sudden death was not activated and someone on your team happened to get tagged?
